# ------------------------------------------------------------------------------
# Create the IAM policy that allows all of the permissions necessary
# to provision the resources required in the assessment account.
# ------------------------------------------------------------------------------
data "aws_iam_policy_document" "policy" {
  statement {
    actions = [
      "acm:DeleteCertificate",
      "acm:DescribeCertificate",
      "acm:RequestCertificate",
      "acm:RemoveTagsFromCertificate",
      "acm:GetCertificate",
      "acm:UpdateCertificateOptions",
      "acm:AddTagsToCertificate",
      "acm:ListCertificates",
      "acm:ListTagsForCertificate",
      "application-autoscaling:RegisterScalableTarget",
      "application-autoscaling:DeleteScheduledAction",
      "application-autoscaling:DescribeScalableTargets",
      "application-autoscaling:DescribeScalingPolicies",
      "application-autoscaling:PutScalingPolicy",
      "application-autoscaling:DescribeScheduledActions",
      "application-autoscaling:DeleteScalingPolicy",
      "application-autoscaling:PutScheduledAction",
      "application-autoscaling:DeregisterScalableTarget",
      "autoscaling-plans:DescribeScalingPlans",
      "autoscaling-plans:UpdateScalingPlan",
      "autoscaling-plans:DeleteScalingPlan",
      "autoscaling-plans:GetScalingPlanResourceForecastData",
      "autoscaling-plans:DescribeScalingPlanResources",
      "autoscaling-plans:CreateScalingPlan",
      "cloudwatch:PutDashboard",
      "cloudwatch:PutMetricData",
      "cloudwatch:GetDashboard",
      "cloudwatch:DeleteAlarms",
      "cloudwatch:GetMetricData",
      "cloudwatch:GetMetricStatistics",
      "cloudwatch:PutCompositeAlarm",
      "cloudwatch:ListMetrics",
      "cloudwatch:PutMetricAlarm",
      "cloudwatch:DeleteDashboards",
      "cloudwatch:DescribeAlarmHistory",
      "cloudwatch:EnableAlarmActions",
      "cloudwatch:DisableAlarmActions",
      "cloudwatch:DescribeAlarmsForMetric",
      "cloudwatch:ListDashboards",
      "cloudwatch:DescribeAlarms",
      "cloudwatch:SetAlarmState",
      "cloudwatch:GetMetricWidgetImage",
      "cognito-idp:UpdateUserPoolDomain",
      "cognito-idp:DeleteUserPool",
      "cognito-idp:ConfirmSignUp",
      "cognito-idp:AdminCreateUser",
      "cognito-idp:CreateGroup",
      "cognito-idp:CreateUserPool",
      "cognito-idp:AdminAddUserToGroup",
      "cognito-idp:DeleteUserPoolDomain",
      "cognito-idp:AdminGetUser",
      "cognito-idp:ListUserPoolClients",
      "cognito-idp:AdminConfirmSignUp",
      "cognito-idp:ListUsersInGroup",
      "cognito-idp:DescribeUserPool",
      "cognito-idp:CreateUserPoolDomain",
      "cognito-idp:AdminEnableUser",
      "cognito-idp:ListGroups",
      "cognito-idp:AdminListDevices",
      "cognito-idp:UpdateGroup",
      "cognito-idp:AdminDisableUser",
      "cognito-idp:AdminRemoveUserFromGroup",
      "cognito-idp:DeleteUser",
      "cognito-idp:DescribeUserPoolClient",
      "cognito-idp:DeleteGroup",
      "cognito-idp:AdminDeleteUser",
      "cognito-idp:GetUser",
      "cognito-idp:SignUp",
      "cognito-idp:DeleteUserPoolClient",
      "cognito-idp:UpdateUserPoolClient",
      "cognito-idp:GetGroup",
      "cognito-idp:ListUserPools",
      "cognito-idp:DescribeUserPoolDomain",
      "cognito-idp:CreateUserPoolClient",
      "cognito-idp:AdminListGroupsForUser",
      "cognito-idp:UpdateUserPool",
      "cognito-idp:AdminResetUserPassword",
      "cognito-idp:ListUsers",
      "ec2:AuthorizeSecurityGroupIngress",
      "ec2:ReplaceRouteTableAssociation",
      "ec2:AttachInternetGateway",
      "ec2:ReplaceRoute",
      "ec2:UpdateSecurityGroupRuleDescriptionsIngress",
      "ec2:AssociateRouteTable",
      "ec2:DeleteRouteTable",
      "ec2:DescribeInternetGateways",
      "ec2:ReplaceNetworkAclEntry",
      "ec2:RevokeSecurityGroupEgress",
      "ec2:CreateRoute",
      "ec2:CreateInternetGateway",
      "ec2:DeleteInternetGateway",
      "ec2:UnassignPrivateIpAddresses",
      "ec2:DescribeNetworkAcls",
      "ec2:DescribeRouteTables",
      "ec2:UpdateSecurityGroupRuleDescriptionsEgress",
      "ec2:CreateTags",
      "ec2:CreateRouteTable",
      "ec2:DeleteNetworkInterface",
      "ec2:DetachInternetGateway",
      "ec2:AssignPrivateIpAddresses",
      "ec2:DisassociateRouteTable",
      "ec2:ReplaceNetworkAclAssociation",
      "ec2:RevokeSecurityGroupIngress",
      "ec2:CreateNetworkInterface",
      "ec2:DeleteNatGateway",
      "ec2:AssociateAddress",
      "ec2:DescribeSubnets",
      "ec2:DeleteNetworkAclEntry",
      "ec2:DisassociateAddress",
      "ec2:DescribeAddresses",
      "ec2:DeleteTags",
      "ec2:CreateNatGateway",
      "ec2:DescribeNetworkInterfaces",
      "ec2:DescribeAvailabilityZones",
      "ec2:CreateSecurityGroup",
      "ec2:CreateNetworkAcl",
      "ec2:DeleteNetworkAcl",
      "ec2:ReleaseAddress",
      "ec2:AuthorizeSecurityGroupEgress",
      "ec2:DetachNetworkInterface",
      "ec2:DescribeTags",
      "ec2:DeleteRoute",
      "ec2:DescribeNatGateways",
      "ec2:AllocateAddress",
      "ec2:DescribeSecurityGroups",
      "ec2:DeleteSecurityGroup",
      "ec2:AttachNetworkInterface",
      "ec2:CreateNetworkAclEntry",
      "ecr:PutLifecyclePolicy",
      "ecr:CreateRepository",
      "ecr:GetDownloadUrlForLayer",
      "ecr:GetAuthorizationToken",
      "ecr:UploadLayerPart",
      "ecr:BatchDeleteImage",
      "ecr:ListImages",
      "ecr:DeleteLifecyclePolicy",
      "ecr:DeleteRepository",
      "ecr:PutImage",
      "ecr:SetRepositoryPolicy",
      "ecr:CompleteLayerUpload",
      "ecr:DescribeImages",
      "ecr:DescribeRepositories",
      "ecr:InitiateLayerUpload",
      "ecr:DeleteRepositoryPolicy",
      "ecr:BatchCheckLayerAvailability",
      "ecr:GetRepositoryPolicy",
      "ecr:GetLifecyclePolicy",
      "ecs:UpdateContainerInstancesState",
      "ecs:StartTask",
      "ecs:RegisterContainerInstance",
      "ecs:DescribeTaskDefinition",
      "ecs:DeregisterTaskDefinition",
      "ecs:ListServices",
      "ecs:UpdateService",
      "ecs:CreateService",
      "ecs:RunTask",
      "ecs:ListTasks",
      "ecs:RegisterTaskDefinition",
      "ecs:StopTask",
      "ecs:DescribeServices",
      "ecs:SubmitContainerStateChange",
      "ecs:DescribeContainerInstances",
      "ecs:DeregisterContainerInstance",
      "ecs:DescribeTasks",
      "ecs:ListTaskDefinitions",
      "ecs:ListClusters",
      "ecs:CreateCluster",
      "ecs:DeleteService",
      "ecs:DeleteCluster",
      "ecs:DescribeClusters",
      "ecs:ListTaskDefinitionFamilies",
      "ecs:UpdateContainerAgent",
      "ecs:ListContainerInstances",
      "ecs:UpdateServicePrimaryTaskSet",
    ]

    resources = [
      "*"
    ]
  }
}

resource "aws_iam_policy" "policy" {
  description = "Policy for running terraform against account."
  name        = "${var.app}-${var.env}-github-actions"
  policy      = data.aws_iam_policy_document.policy.json
}

data "aws_iam_policy_document" "policy2" {
  statement {
    actions = [
      "elasticloadbalancing:ModifyListener",
      "elasticloadbalancing:RegisterTargets",
      "elasticloadbalancing:SetIpAddressType",
      "elasticloadbalancing:SetRulePriorities",
      "elasticloadbalancing:RemoveListenerCertificates",
      "elasticloadbalancing:DeleteLoadBalancer",
      "elasticloadbalancing:SetWebAcl",
      "elasticloadbalancing:DescribeLoadBalancers",
      "elasticloadbalancing:RemoveTags",
      "elasticloadbalancing:CreateListener",
      "elasticloadbalancing:DescribeListeners",
      "elasticloadbalancing:CreateRule",
      "elasticloadbalancing:DescribeListenerCertificates",
      "elasticloadbalancing:AddListenerCertificates",
      "elasticloadbalancing:ModifyTargetGroupAttributes",
      "elasticloadbalancing:DeleteRule",
      "elasticloadbalancing:DescribeSSLPolicies",
      "elasticloadbalancing:CreateLoadBalancer",
      "elasticloadbalancing:CreateTargetGroup",
      "elasticloadbalancing:DeregisterTargets",
      "elasticloadbalancing:SetSubnets",
      "elasticloadbalancing:DeleteTargetGroup",
      "elasticloadbalancing:DescribeLoadBalancerAttributes",
      "elasticloadbalancing:DescribeTargetGroupAttributes",
      "elasticloadbalancing:ModifyRule",
      "elasticloadbalancing:AddTags",
      "elasticloadbalancing:DescribeTargetHealth",
      "elasticloadbalancing:SetSecurityGroups",
      "elasticloadbalancing:DescribeTargetGroups",
      "elasticloadbalancing:DescribeRules",
      "elasticloadbalancing:ModifyLoadBalancerAttributes",
      "elasticloadbalancing:ModifyTargetGroup",
      "elasticloadbalancing:DeleteListener",
      "events:PutEvents",
      "events:DescribeRule",
      "events:EnableRule",
      "events:CreateEventBus",
      "events:PutRule",
      "events:DeactivateEventSource",
      "events:DescribeEventSource",
      "events:ListEventBuses",
      "events:PutPermission",
      "events:DescribeEventBus",
      "events:DeleteRule",
      "events:PutTargets",
      "events:ListRuleNamesByTarget",
      "events:ListEventSources",
      "events:DeleteEventBus",
      "events:ListRules",
      "events:RemovePermission",
      "events:RemoveTargets",
      "events:ListTargetsByRule",
      "events:DisableRule",
      "lambda:CreateFunction",
      "lambda:ListVersionsByFunction",
      "lambda:GetLayerVersion",
      "lambda:PublishLayerVersion",
      "lambda:DeleteProvisionedConcurrencyConfig",
      "lambda:GetFunctionConfiguration",
      "lambda:CreateEventSourceMapping",
      "lambda:GetLayerVersionPolicy",
      "lambda:RemoveLayerVersionPermission",
      "lambda:PutFunctionConcurrency",
      "lambda:ListProvisionedConcurrencyConfigs",
      "lambda:GetProvisionedConcurrencyConfig",
      "lambda:DeleteLayerVersion",
      "lambda:PutFunctionEventInvokeConfig",
      "lambda:DeleteFunctionEventInvokeConfig",
      "lambda:ListLayerVersions",
      "lambda:ListLayers",
      "lambda:DeleteFunction",
      "lambda:UpdateFunctionEventInvokeConfig",
      "lambda:UpdateEventSourceMapping",
      "lambda:ListFunctions",
      "lambda:GetEventSourceMapping",
      "lambda:InvokeFunction",
      "lambda:GetFunction",
      "lambda:UpdateFunctionConfiguration",
      "lambda:AddLayerVersionPermission",
      "lambda:UpdateFunctionCode",
      "lambda:ListFunctionEventInvokeConfigs",
      "lambda:GetFunctionConcurrency",
      "lambda:GetFunctionEventInvokeConfig",
      "lambda:PutProvisionedConcurrencyConfig",
      "lambda:ListEventSourceMappings",
      "lambda:DeleteFunctionConcurrency",
      "lambda:DeleteEventSourceMapping",
      "logs:GetLogRecord",
      "logs:DescribeLogGroups",
      "logs:UntagLogGroup",
      "logs:DeleteLogGroup",
      "logs:DescribeLogStreams",
      "logs:DescribeMetricFilters",
      "logs:CreateLogGroup",
      "logs:DeleteLogStream",
      "logs:PutLogEvents",
      "logs:PutMetricFilter",
      "logs:DeleteResourcePolicy",
      "logs:PutResourcePolicy",
      "logs:CreateLogStream",
      "logs:DeleteMetricFilter",
      "logs:TagLogGroup",
      "logs:DeleteRetentionPolicy",
      "logs:GetLogEvents",
      "logs:FilterLogEvents",
      "logs:PutRetentionPolicy",
      "logs:GetLogGroupFields",
      "logs:DescribeResourcePolicies",
      "rds:StartDBCluster",
      "rds:DescribeDBInstanceAutomatedBackups",
      "rds:RestoreDBInstanceFromS3",
      "rds:ResetDBParameterGroup",
      "rds:DescribeEngineDefaultParameters",
      "rds:CreateOptionGroup",
      "rds:CreateDBSubnetGroup",
      "rds:ModifyDBParameterGroup",
      "rds:CopyDBParameterGroup",
      "rds:ModifyDBInstance",
      "rds:ModifyDBClusterParameterGroup",
      "rds:ModifyDBClusterSnapshotAttribute",
      "rds:DeleteDBInstance",
      "rds:CreateDBClusterEndpoint",
      "rds:StopDBCluster",
      "rds:CreateDBParameterGroup",
      "rds:DescribeDBSnapshots",
      "rds:DeleteDBSnapshot",
      "rds:DescribeDBSecurityGroups",
      "rds:DeleteDBInstanceAutomatedBackup",
      "rds:StartDBInstance",
      "rds:RestoreDBClusterFromS3",
      "rds:DeleteDBSubnetGroup",
      "rds:CreateDBSnapshot",
      "rds:RestoreDBInstanceFromDBSnapshot",
      "rds:DeleteDBSecurityGroup",
      "rds:ModifyDBClusterEndpoint",
      "rds:ModifyDBCluster",
      "rds:CreateDBClusterSnapshot",
      "rds:DeleteDBParameterGroup",
      "rds:CreateDBClusterParameterGroup",
      "rds:ModifyDBSnapshotAttribute",
      "rds:DescribeOptionGroups",
      "rds:AuthorizeDBSecurityGroupIngress",
      "rds:CreateEventSubscription",
      "rds:ModifyOptionGroup",
      "rds:RestoreDBClusterFromSnapshot",
      "rds:DescribeDBSubnetGroups",
      "rds:DescribeDBParameterGroups",
      "rds:DeleteOptionGroup",
      "rds:DeleteEventSubscription",
      "rds:CreateDBInstance",
      "rds:DeleteDBClusterEndpoint",
      "rds:DescribeDBInstances",
      "rds:DescribeEngineDefaultClusterParameters",
      "rds:RevokeDBSecurityGroupIngress",
      "rds:DescribeDBParameters",
      "rds:DescribeEventCategories",
      "rds:DeleteDBCluster",
      "rds:ResetDBClusterParameterGroup",
      "rds:RestoreDBClusterToPointInTime",
      "rds:DescribeEvents",
      "rds:DescribeDBClusterSnapshotAttributes",
      "rds:DescribeDBClusterParameters",
      "rds:DescribeEventSubscriptions",
      "rds:CopyDBSnapshot",
      "rds:CopyDBClusterSnapshot",
      "rds:ModifyEventSubscription",
      "rds:StopDBInstance",
      "rds:CopyOptionGroup",
      "rds:DescribeDBSnapshotAttributes",
      "rds:ModifyDBSnapshot",
      "rds:DeleteDBClusterSnapshot",
      "rds:CreateDBCluster",
      "rds:CreateDBSecurityGroup",
      "rds:RebootDBInstance",
      "rds:DescribeDBClusterSnapshots",
      "rds:DescribeOptionGroupOptions",
      "rds:DescribeDBClusterEndpoints",
      "rds:DeleteDBClusterParameterGroup",
      "rds:DescribeDBClusters",
      "rds:DescribeDBClusterParameterGroups",
      "rds:ModifyDBSubnetGroup",
      "rds:RestoreDBInstanceToPointInTime",
      "route53:CreateHostedZone",
      "route53:GetHostedZone",
      "route53:ListHostedZones",
      "route53:ChangeResourceRecordSets",
      "route53:ListResourceRecordSets",
      "route53:DeleteHostedZone",
      "route53:GetHostedZoneCount",
      "route53:ListHostedZonesByName"
    ]

    resources = [
      "*"
    ]
  }
}

resource "aws_iam_policy" "policy2" {
  description = "Policy for running terraform against account."
  name        = "${var.app}-${var.env}-github-actions-2"
  policy      = data.aws_iam_policy_document.policy2.json
}

data "aws_iam_policy_document" "policy3" {
  statement {
    actions = [
      "s3:GetBucketTagging",
      "s3:GetBucketLogging",
      "s3:RestoreObject",
      "s3:CreateBucket",
      "s3:ListBucket",
      "s3:GetBucketPolicy",
      "s3:ReplicateObject",
      "s3:GetObjectAcl",
      "s3:DeleteBucketWebsite",
      "s3:PutBucketTagging",
      "s3:PutBucketAcl",
      "s3:DeleteObject",
      "s3:DeleteBucket",
      "s3:PutObjectAcl",
      "s3:PutBucketPublicAccessBlock",
      "s3:GetBucketWebsite",
      "s3:GetBucketAcl",
      "s3:GetBucketNotification",
      "s3:DeleteBucketPolicy",
      "s3:PutObject",
      "s3:GetObject",
      "s3:PutBucketNotification",
      "s3:PutBucketWebsite",
      "s3:ListAllMyBuckets",
      "s3:PutBucketLogging",
      "s3:PutBucketPolicy",
      "s3:GetBucketLocation",
      "sns:ListSubscriptionsByTopic",
      "sns:GetTopicAttributes",
      "sns:DeleteTopic",
      "sns:CreateTopic",
      "sns:ListTopics",
      "sns:Unsubscribe",
      "sns:SetTopicAttributes",
      "sns:GetSubscriptionAttributes",
      "sns:ListSubscriptions",
      "sns:SetSubscriptionAttributes",
      "sns:Publish",
      "sns:Subscribe",
      "sns:ConfirmSubscription",
      "sqs:DeleteMessage",
      "sqs:ListQueues",
      "sqs:RemovePermission",
      "sqs:GetQueueUrl",
      "sqs:ListDeadLetterSourceQueues",
      "sqs:AddPermission",
      "sqs:PurgeQueue",
      "sqs:ReceiveMessage",
      "sqs:DeleteQueue",
      "sqs:GetQueueAttributes",
      "sqs:CreateQueue",
      "sqs:SetQueueAttributes",
      "ssm:PutParameter",
      "ssm:LabelParameterVersion",
      "ssm:DeleteParameter",
      "ssm:DescribeParameters",
      "ssm:GetParameterHistory",
      "ssm:DescribeDocumentParameters",
      "ssm:GetParametersByPath",
      "ssm:GetParameters",
      "ssm:GetParameter",
      "ssm:DeleteParameters",
      "ssm:*Tags*",
      "sts:AssumeRole",
      "sts:GetCallerIdentity"
    ]

    resources = [
      "*"
    ]
  }
}

resource "aws_iam_policy" "policy3" {
  description = "Policy for running terraform against account."
  name        = "${var.app}-${var.env}-github-actions-3"
  policy      = data.aws_iam_policy_document.policy3.json
}




# ------------------------------------------------------------------------------
# Attach to the ProvisionAccount role the IAM policy that allows
# provisioning of the resources required.
# ------------------------------------------------------------------------------
resource "aws_iam_role_policy_attachment" "policy" {
  policy_arn = aws_iam_policy.policy.arn
  role       = var.provision_account_role_name
}

resource "aws_iam_role_policy_attachment" "policy2" {
  policy_arn = aws_iam_policy.policy2.arn
  role       = var.provision_account_role_name
}

resource "aws_iam_role_policy_attachment" "policy3" {
  policy_arn = aws_iam_policy.policy3.arn
  role       = var.provision_account_role_name
}
