---
version: "3"
services:
  mongodb_container:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_ROOT_USERNAME: root
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data_container:/data/db"
volumes:
  mongodb_data_container: ~
