# This is a Makefile for dev and deployment commands
test:
	echo "No tests at base level ..."

# target: up - Run local web server.
up:
	 docker-compose up -d

# target: stop - Stop all docker containers
stop:
	docker-compose stop

# target: down - Remove all docker containers
down:
	docker-compose down
