# This is a Makefile for dev and deployment commands
test:
	echo "No tests at base level ..."

# target: build = build all containers
docker-build:
	docker-compose build

# target: up - Run local web server.
docker-up:
	 docker-compose up -d

# target: stop - Stop all docker containers
docker-stop:
	docker-compose stop

# target: down - Remove all docker containers
docker-down:
	docker-compose down
