---
version: "3"
services:
  mongodb:
    container_name: cpa-mongodb
    hostname: mongodb
    image: "mongo:3.6"
    # These ports are exposed on the host; 'hostport:containerport'.
    # You could connect to this server from outside with the *host's*
    # DNS name or IP address and port 27017 (the left-hand side of the
    # colon).
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "mongodb:/data/db"
    env_file:
      - ../base/mongodb/.env

# Host volumes used to store code.
volumes:
  mongodb:
