# This is a Makefile for dev and deployment commands
test:
	echo "No tests at base level ..."

docker-up:
	make up -C ./mongodb

docker-stop:
	make stop -C ./mongodb

docker-down:
	make down -C ./mongodb
