---
name: Sandbox Deploy

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
  repository_dispatch:
    types: [deploy]

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  ECR_URI: ${{ secrets.ECR_URI }}
  ENVIRONMENT: dev
  REGION: us-east-1
  SES_ARN: ${{ secrets.SES_ROLE_ARN }}

jobs:
  build_ui:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: con-pca-web
    environment:
      name: develop
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cisagov/con-pca-web
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::$(git rev-parse --short HEAD)
      - name: Build Docker Image
        run: docker build -f Dockerfile -t $IMAGE_REPO:${{steps.vars.outputs.tag}} .
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: Tag Docker Image
        run: docker tag $IMAGE_REPO:${{steps.vars.outputs.tag}} $ECR_URI/$IMAGE_REPO:${{steps.vars.outputs.tag}}
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: ECR Login
        run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI/$IMAGE_REPO
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: Push Docker Image
        run: docker push $ECR_URI/$IMAGE_REPO:${{steps.vars.outputs.tag}}
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}

  build_api:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: con-pca-api
    environment:
      name: develop
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cisagov/con-pca-api
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::$(git rev-parse --short HEAD)
      - name: Build Docker Image
        run: docker build -f Dockerfile -t $IMAGE_REPO:${{steps.vars.outputs.tag}} .
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: Tag Docker Image
        run: docker tag $IMAGE_REPO:${{steps.vars.outputs.tag}} $ECR_URI/$IMAGE_REPO:${{steps.vars.outputs.tag}}
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: ECR Login
        run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI/$IMAGE_REPO
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: Push Docker Image
        run: docker push $ECR_URI/$IMAGE_REPO:${{steps.vars.outputs.tag}}
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}

  terraform:
    runs-on: ubuntu-latest
    needs: [build_ui, build_api]
    defaults:
      run:
        working-directory: terraform
    environment:
      name: develop

    steps:
      # Checkout cicd repo for running terraform
      - uses: actions/checkout@v2

      # Install Terraform
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~1.1
      - name: Verify Terraform version
        run: terraform --version

      # Initialize Terraform
      - name: Terraform init
        run: terraform init -input=false

      # Create terraform workspace
      - name: Create Terraform Workspace
        run: |
          terraform workspace new $ENVIRONMENT
        continue-on-error: true

      # Select terraform workspace
      - name: Select Terraform Workspace
        run: |
          terraform workspace select $ENVIRONMENT
          terraform workspace show

      # Validate Terraform
      - name: Terraform validation
        run: terraform validate

      # Sometimes this just needs run again...
      - name: Terraform init 2
        run: terraform init -input=false

      # Plan terraform
      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -var-file ./vars/$ENVIRONMENT.tfvars \
            -var="account_id=$ACCOUNT_ID" \
            -var="api_image_tag=${{needs.build_api.outputs.tag}}" \
            -var="ui_image_tag=${{needs.build_ui.outputs.tag}}" \
            -var="ses_arn=$SES_ARN" \
            -var="deployed_date=$(date)" \
            -var="mailgun_api_key=$MAILGUN_API_KEY" \
            -var="maxmind_user_id"=${{secrets.MAXMIND_USER_ID}} \
            -var="maxmind_license_key=${{secrets.MAXMIND_LICENSE_KEY}}"

      # Apply terraform
      - name: Terraform Apply
        run: |
          terraform apply \
            -input=false -auto-approve \
            -var-file ./vars/$ENVIRONMENT.tfvars \
            -var="account_id=$ACCOUNT_ID" \
            -var="api_image_tag=${{needs.build_api.outputs.tag}}" \
            -var="ui_image_tag=${{needs.build_ui.outputs.tag}}" \
            -var="ses_arn=$SES_ARN" \
            -var="deployed_date=$(date)" \
            -var="mailgun_api_key=$MAILGUN_API_KEY" \
            -var="maxmind_user_id"=${{secrets.MAXMIND_USER_ID}} \
            -var="maxmind_license_key=${{secrets.MAXMIND_LICENSE_KEY}}"
        if: ${{ github.event_name != 'pull_request' }}
